

CREATE TABLE public.address_location (
    id bigint NOT NULL,
    complemento character varying(255),
    ddd character varying(255),
    gia character varying(255),
    ibge character varying(255),
    localidade character varying(255),
    logradouro character varying(255),
    siafi character varying(255),
    uf character varying(255)
);


--
-- Name: address_location_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.address_location ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.address_location_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tb_doctor; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tb_doctor (
    id bigint NOT NULL,
    cep character varying(255),
    crm character varying(255) NOT NULL,
    name character varying(120) NOT NULL,
    phone character varying(255),
    phone_fix character varying(255),
    address_id bigint
);


--
-- Name: tb_doctor_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tb_doctor ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tb_doctor_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tb_doctors_specialties; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tb_doctors_specialties (
    doctor_id bigint NOT NULL,
    specialtie_id bigint NOT NULL
);


--
-- Name: tb_specialties; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tb_specialties (
    id bigint NOT NULL,
    deleted boolean NOT NULL,
    name character varying(255) NOT NULL
);


--
-- Name: tb_specialties_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tb_specialties ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tb_specialties_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: address_location address_location_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.address_location
    ADD CONSTRAINT address_location_pkey PRIMARY KEY (id);


--
-- Name: tb_doctor tb_doctor_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_doctor
    ADD CONSTRAINT tb_doctor_pkey PRIMARY KEY (id);


--
-- Name: tb_doctors_specialties tb_doctors_specialties_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_doctors_specialties
    ADD CONSTRAINT tb_doctors_specialties_pkey PRIMARY KEY (doctor_id, specialtie_id);


--
-- Name: tb_specialties tb_specialties_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_specialties
    ADD CONSTRAINT tb_specialties_pkey PRIMARY KEY (id);


--
-- Name: tb_doctors_specialties fk2ejyskc1jetimtmqguf9jhvti; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_doctors_specialties
    ADD CONSTRAINT fk2ejyskc1jetimtmqguf9jhvti FOREIGN KEY (doctor_id) REFERENCES public.tb_doctor(id);


--
-- Name: tb_doctors_specialties fkhr1tbffokjn67mdd0sht6rne7; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_doctors_specialties
    ADD CONSTRAINT fkhr1tbffokjn67mdd0sht6rne7 FOREIGN KEY (specialtie_id) REFERENCES public.tb_specialties(id);


--
-- Name: tb_doctor fktnda70jk2kfa43ijfhjf1p38d; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_doctor
    ADD CONSTRAINT fktnda70jk2kfa43ijfhjf1p38d FOREIGN KEY (address_id) REFERENCES public.address_location(id);


--
-- PostgreSQL database dump complete
--

