INSERT INTO TB_SPECIALTIES VALUES (1, 0, 'ALERGOLOGIA');
INSERT INTO TB_SPECIALTIES VALUES (2, 0, 'BANGIOLOGIA');
INSERT INTO TB_SPECIALTIES VALUES (3, 0, 'BUCO MAXILO');
INSERT INTO TB_SPECIALTIES VALUES (4, 0, 'CARDIOLOGIA CLÍNICA');
INSERT INTO TB_SPECIALTIES VALUES (5, 0, 'CARDIOLOGIA INFANTIL');
INSERT INTO TB_SPECIALTIES VALUES (6, 0, 'CIRURGIA CABEÇA E PESCOÇO');
INSERT INTO TB_SPECIALTIES VALUES (7, 0, 'CIRURGIA CABEÇA E PESCOÇO');
INSERT INTO TB_SPECIALTIES VALUES (8, 0, 'CIRURGIA DE TÓRAX');


